BEGIN TRANSACTION;
CREATE TABLE "TRACKS" (
	`TRACKID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`TRACKNAME`	TEXT NOT NULL,
	`DURATION`	INTEGER NOT NULL,
	`ARTIST`	INTEGER NOT NULL,
	`GENRE`	INTEGER NOT NULL,
	`ALBUM`	INTEGER NOT NULL,
	FOREIGN KEY(`ARTIST`) REFERENCES ARTISTID
);
CREATE TABLE `SUBSCRIPTION` (
	`USERID`	INTEGER NOT NULL UNIQUE,
	`PREMIUM`	INTEGER NOT NULL DEFAULT 0,
	`SUBSCRIPTION TYPE`	INTEGER NOT NULL DEFAULT 0,
	`DUEDATE`	INTEGER,
	`PAID`	INTEGER,
	FOREIGN KEY(`USERID`) REFERENCES ID
);
CREATE TABLE "PLAYLIST-TRACK" (
	`PLAYLISTID`	INTEGER NOT NULL CHECK(PLAYLISTID),
	`TRACK`	INTEGER NOT NULL,
	FOREIGN KEY(`TRACK`) REFERENCES `TRACKID`
);
CREATE TABLE "PLAYLIST" (
	`PLAYLISTID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PLAYLISTOWNER`	INTEGER NOT NULL,
	FOREIGN KEY(`PLAYLISTOWNER`) REFERENCES `ID`
);
CREATE TABLE `FRIENDLIST-FRIEND` (
	`FLID`	INTEGER NOT NULL,
	`FRIEND`	INTEGER NOT NULL,
	FOREIGN KEY(`FLID`) REFERENCES FRIENDLISTID,
	FOREIGN KEY(`FRIEND`) REFERENCES ID
);
CREATE TABLE "FRIENDLIST" (
	`FRIENDLISTID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`LISTOWNER`	INTEGER NOT NULL,
	FOREIGN KEY(`LISTOWNER`) REFERENCES ID
);
CREATE TABLE `DEVICELIST-DEVICE` (
	`DLID`	INTEGER NOT NULL,
	`DEVICE`	INTEGER NOT NULL,
	FOREIGN KEY(`DLID`) REFERENCES DEVICELISTID,
	FOREIGN KEY(`DEVICE`) REFERENCES DEVICEID
);
CREATE TABLE `DEVICELIST` (
	`DEVICELIST`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`DEVICEOWNER`	INTEGER NOT NULL,
	FOREIGN KEY(`DEVICEOWNER`) REFERENCES ID
);
CREATE TABLE "DEVICE" (
	`DEVICEID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`DEVICE NAME`	TEXT NOT NULL,
	`DEVICE TYPE`	TEXT NOT NULL,
	`DATE`	INTEGER NOT NULL
);
CREATE TABLE `ARTIST` (
	`ARTISTID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ARTISTNAME`	INTEGER NOT NULL
);
CREATE TABLE `ACCOUNT` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`USERNAME`	TEXT NOT NULL,
	`PASSWORD`	TEXT NOT NULL,
	`FIRSTNAME`	TEXT NOT NULL,
	`LASTNAME`	TEXT NOT NULL,
	`DOORNO`	TEXT NOT NULL,
	`STREET`	TEXT NOT NULL,
	`CITY`	TEXT NOT NULL,
	`COUNTY`	TEXT NOT NULL DEFAULT 'N/A',
	`POSTCODE`	TEXT NOT NULL,
	`CONTACTNO`	TEXT NOT NULL
);
COMMIT;
